Added context string consideration
lamps-wg/draft-composite-sigs pull request #38
Opened 2024-08-29 20:50 UTC by feventura

Added context string consideration, as defined in #35.

2024-09-25 14:38 UTC, ounsworth commented
Do not merge, we decided to do this differently. See comments #42

2024-09-26 12:12 UTC, janklaussner commented
Closes #42

2024-10-06 09:21 UTC, ounsworth requested changes

2024-10-06 09:21 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +        IF (S1 != NULL) and (S2 != NULL):
Where does this IF statement come from? I don't see an equivalent in FIPS 204 in either Algorithm 2 or Algorithm 7. I appreciate the attempt at error-handling, but I'm not sure that this notation really works because FIPS 204 talks about returning an error or "⊥", but does not talk about returning NULL. I will replace this with an English sentence about error handling.

2024-10-06 09:21 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +                        section on pre-hashing the message below.
Which "section on pre-hashing the message" is this referring to? I don't see one.

2024-10-09 17:08 UTC, johngray-dev commented
All the changes in this pull request are now in #59 which will eventually get pushed to main

2024-10-09 17:08 UTC, closed without merging