Integrate issue35 with main
lamps-wg/draft-composite-sigs pull request #59
Opened 2024-10-09 17:05 UTC by johngray-dev

Updating the pull request to have the latest main changes for adding the context String and the pure and pre-hash modes of composite.

2024-10-13 09:59 UTC, ounsworth requested changes

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +A composite signature's value MUST include two signature components and MUST be in the same order as the components from the corresponding signing key.
```suggestion
A composite signature's value MUST include two signature components and MUST be in the same order as the components from the corresponding verification public key.
```

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +   2. Compute the Message format M' by concatenating the Domain identifier (i.e., the DER encoding of the Composite signature algorithm identifier) with the length of ctx, the value ctx and the M
```suggestion
   2. Compute the Message M' by concatenating the Domain identifier (i.e., the DER encoding of the Composite signature algorithm identifier) with the length of ctx, the value ctx and the original message M
```

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +This mode mirrors `ML-DSA.Sign(sk, M, ctx)` defined in Section 5.3 of [FIPS.204]. Verification of a composite signature involves reconstructing the `M'` message by concatenating the composite domain
```suggestion
This mode mirrors `ML-DSA.Verify(pk, M, signature, ctx)` defined in Section 5.3 of [FIPS.204]. Verification of a composite signature involves reconstructing the `M'` message by concatenating the composite domain separator "Domain" {{sec-oid-concat}} with the length of the context string `ctx` in bytes, the context string `ctx`, and finally the original message `M` .
```

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +      composite then output "Invalid signature" and stop.
This whole paragraph needs to be re-done. The prohibition of recursive composites is a hold-over from generics and no longer makes sense.

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +   2. If |ctx| > 255
The order of steps should be synced with .Sign(). For example, ,Sign() has 

```
1. If |ctx| > 255
2. Compute the Message format M'
3. Separate the private key into componet keys.
```

But here in .Verify(), we have:

```
1. Separate the keys and signatures
2. If |ctx| > 255
3. Format the Message as follows
```

I think the order in .Verify() makes more sense, so we should change .Sign() to match.

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +   3. Format the Message as follows:
```suggestion
   3. Compute the Message M' by concatenating the Domain identifier (i.e., the DER encoding of the Composite signature algorithm identifier) with the length of ctx, the value ctx and the original message M
```

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +{: #alg-hash-composite-sign title="HashComposite-ML-DSA-Sign(sk, M, ctx, PH)"}
Again, we should make sure that the order of steps is aligned with the pure algs above.

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +{: #alg-hash-composite-verify title="Hash-Composite-ML-DSA-Verify(pk, M, signature, ctx, PH)"}
Again, we should make sure that the order of steps is aligned with the pure algs above.

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +The following tables summarizes the details for each explicit composite signature algorithms:
```suggestion
The following tables summarize the details for each explicit composite signature algorithms:
```

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +| id-MLDSA44-Ed25519                  | &lt;CompSig&gt;.23 | id-ML-DSA-44  | id-Ed25519 | Not Needed |
```suggestion
| id-MLDSA44-Ed25519                  | &lt;CompSig&gt;.23 | id-ML-DSA-44  | id-Ed25519 | None |
```

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +| id-MLDSA65-Ed25519                      | &lt;CompSig&gt;.30  | id-ML-DSA-65 | id-Ed25519 | Not Needed |
```suggestion
| id-MLDSA65-Ed25519                      | &lt;CompSig&gt;.30  | id-ML-DSA-65 | id-Ed25519 | None |
```

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +| id-MLDSA87-Ed448                        | &lt;CompSig&gt;.33 | id-ML-DSA-87 | id-Ed448 | Not Needed |
```suggestion
| id-MLDSA87-Ed448                        | &lt;CompSig&gt;.33 | id-ML-DSA-87 | id-Ed448 | None |
```

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +Pure Signature public key types:
```suggestion
Pure Composite-ML-DSA Signature public key types:
```

2024-10-13 09:59 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +HashML-DSA Signature public key types:
```suggestion
HashComposite-ML-DSA Signature public key types:
```

2024-10-16 14:27 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-sigs.md
> +      composite then output "Invalid signature" and stop.
Suggestion:

      If Error during Desequencing, or if any of the component keys or signature values are not of the correct key type or length for the given component algorithm then output "Invalid signature" and stop.

2024-10-16 14:32 UTC, johngray-dev commented on draft-ietf-lamps-pq-composite-sigs.md
> +   3. Separate the private key into componet keys. Note, the exact storage format for composite private keys may be as described in this document, or may be implementation-specific.
typo in component

2024-10-16 17:16 UTC, johngray-dev commented on draft-ietf-lamps-pq-composite-sigs.md
> +| id-MLDSA44-Ed25519                  | &lt;CompSig&gt;.23 | id-ML-DSA-44  | id-Ed25519 | Not Needed |
Group agreed with this change.

2024-10-16 17:22 UTC, johngray-dev commented on draft-ietf-lamps-pq-composite-sigs.md
> +   2. If |ctx| > 255
I don't agree.   If we want to change them to be the same order, then we change Verify.     In Sign() if ctx > 255 then computing M' would fail because the length of the context can't be encoded into a single byte and computing M' would fail or be incorrect.  Why do all that when a simple check of the length would tell us if we can encode M' properly?    For verify, I don't really think the order matters as separating the keys is independent of the context check, but since the context check is faster, lets just do that one first in verify so they match up...

2024-10-16 19:26 UTC, johngray-dev commented on draft-ietf-lamps-pq-composite-sigs.md
> +   2. If |ctx| > 255
I made the change to Verify so the two now match.  The first step is now the context check in a cases (both for pure and pre-hash).

2024-10-17 19:03 UTC, ounsworth approved these changes

2024-10-17 19:08 UTC, merged